import fs from 'node:fs';import path from 'node:path';
const site='https://stockcut.ymirtool.com';
const pages=['/','/sheet-cutting-optimizer','/linear-cutting-optimizer','/saw-kerf-calculator','/plywood-cutting-layout-calculator','/4x8-plywood-cut-list-optimizer','/mdf-sheet-cut-calculator','/acrylic-sheet-cutting-layout-tool','/cabinet-cut-list-optimizer','/bookshelf-cut-list-calculator','/steel-tube-cutting-optimizer','/aluminum-extrusion-cut-list-optimizer','/how-to-account-for-saw-kerf','/guillotine-cut-vs-nesting','/cut-list-optimizer-vs-excel','/privacy','/terms','/disclaimer','/about'];
const titles={
'/':'StockCut — Free Sheet Cutting Optimizer with Kerf','/sheet-cutting-optimizer':'Sheet Cutting Optimizer — StockCut','/linear-cutting-optimizer':'Linear Cutting Optimizer — StockCut','/saw-kerf-calculator':'Saw Kerf Calculator — StockCut','/privacy':'Privacy Policy — StockCut','/terms':'Terms of Use — StockCut','/disclaimer':'Disclaimer — StockCut','/about':'About StockCut'};
const mode=p=>p.includes('linear')||p.includes('steel-tube')||p.includes('aluminum-extrusion')?'linear':p.includes('kerf')?'kerf':p.includes('privacy')||p.includes('terms')||p.includes('disclaimer')?'legal':'sheet';
fs.rmSync('dist',{recursive:true,force:true});fs.mkdirSync('dist/assets',{recursive:true});fs.copyFileSync('src/app.js','dist/assets/app.js');fs.copyFileSync('src/styles.css','dist/assets/styles.css');
function esc(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function outPath(p){return p==='/'?'dist/index.html':`dist${p}/index.html`}
function html(p){const title=titles[p]||`${p.slice(1).split('-').map(w=>w[0].toUpperCase()+w.slice(1)).join(' ')} — StockCut`;const desc='Free local-first cut list optimizer with kerf, units, sheet and linear layouts, labels, waste, offcuts, CSV/JSON export, print/PDF output, and browser-only processing.';return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${desc}"><link rel="canonical" href="${site}${p==='/'?'':p}"><link rel="stylesheet" href="/assets/styles.css"><script type="application/ld+json">{"@context":"https://schema.org","@type":"WebApplication","name":"StockCut","applicationCategory":"UtilitiesApplication","offers":{"@type":"Offer","price":"0","priceCurrency":"USD"}}</script></head><body data-mode="${mode(p)}"><header><a href="/" class="logo">StockCut</a><nav><a href="/sheet-cutting-optimizer">Sheet</a><a href="/linear-cutting-optimizer">Linear</a><a href="/saw-kerf-calculator">Kerf</a><a href="/4x8-plywood-cut-list-optimizer">4×8 Plywood</a><a href="/steel-tube-cutting-optimizer">Steel Tube</a></nav></header><main><section class="hero"><h1>${esc(title.replace(' — StockCut',''))}</h1><p>${desc}</p><p class="badges"><span>Local calculation</span><span>Kerf-aware</span><span>Print / PDF</span><span>CSV / JSON</span></p></section><div id="tool"></div><section class="card"><h2>Scope and safety</h2><p>StockCut produces practical optimized layouts, not guaranteed industrial optimums, CNC files, DXF, G-code, angle cuts, non-rectangular nesting, or engineering instructions. Verify dimensions and shop safety before cutting.</p></section><div class="ad">Advertisement</div><section class="card"><h2>FAQ</h2><details><summary>Does StockCut upload my cut list?</summary><p>No. Calculations and autosave run in your browser. Privacy page explains local processing.</p></details><details><summary>How is kerf handled?</summary><p>2D kerf is treated as spacing between adjacent rectangular parts. 1D kerf is counted between consecutive cuts.</p></details><details><summary>Can I save as PDF?</summary><p>Use Export PDF / Print, then choose Save as PDF in your browser.</p></details></section></main><footer><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/disclaimer">Disclaimer</a><a href="/about">About</a></footer><script type="module" src="/assets/app.js"></script></body></html>`}
for(const p of pages){const f=outPath(p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,html(p))}
fs.writeFileSync('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${site}/sitemap.xml\n`);fs.writeFileSync('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(p=>`<url><loc>${site}${p==='/'?'':p}</loc></url>`).join('')}</urlset>`);console.log(`Built ${pages.length} pages into dist/`);
